### PR TITLE
Fixed cleanup step in test.jenkinsfile

### PR DESCRIPTION
**Pull request by TeoPXL**

### CODE REVIEW

**Review by SeppeBaerts — CHANGES_REQUESTED** [review]
Could you also change "TINnode-devops" to 'testenvnode'

**Review by SeppeBaerts — APPROVED** [review]
Looks good

**Comment by IanVanDenBergh** [comment]
nicly done

**Comment by IanVanDenBergh** [comment]
nicly done

**Review by IanVanDenBergh — APPROVED** [review]
beter done

**Pull request merged**
